name: mvp
description: MVP

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.29+29

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.1
  provider: 6.0.1
  internet_connection_checker: ^0.0.1
  easy_dynamic_theme: ^2.2.0
  sembast: 3.0.2
  path_provider: 2.0.1
  url_launcher: ^6.0.4
  image_picker: 0.7.5+2
  progress_dialog_null_safe: ^1.0.7
  easy_localization: ^3.0.1-dev
  launch_review: 3.0.1
  package_info: 2.0.0
  fluttertoast: 8.0.7
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.7
  firebase_core: ^1.22.0
  azlistview: ^2.0.0
  lpinyin: 2.0.3
  flutter_slidable: 0.6.0
  flutter_switch: 0.3.1
  graphql: ^5.1.1
  firebase_messaging: ^13.0.2
  quiver: ^3.0.1
  android_alarm_manager_plus: ^1.2.0
  workmanager: ^0.5.0
  carousel_slider: 4.0.0-nullsafety.0
  flutter_svg: ^0.22.0
  in_app_update: ^3.0.0
  flutter_screenutil: ^5.5.2
  audioplayers: ^1.0.1
  image_cropper: ^1.5.0
  #  firebase_crashlytics: ^2.3.0
  timeago: ^3.1.0
  flutter_spinkit: ^5.0.0
  device_info_plus: ^4.0.2
  event_bus: ^2.0.0
  jwt_decode: ^0.3.1
  substring_highlight: ^1.0.33
  functional_widget: ^0.9.0+2
  wakelock: ^0.6.0+1
  no_context_navigation: ^2.1.2
  mockito: ^5.0.15
  page_transition: ^2.0.2
  flutter_libphonenumber: ^1.2.4
  intl_phone_number_input: ^0.7.0+2
  fcm_unrealistic_heartbeat: ^0.0.3
  percent_indicator: ^4.2.2
  wifi_iot: ^0.3.14
  encrypt: ^5.0.1
  shimmer: ^2.0.0
  contacts_service: ^0.6.3
  intercom_flutter: ^7.2.0
  app_settings: ^4.0.0
  pull_to_refresh: ^2.0.0
  visibility_detector: ^0.3.3
  flutter_statusbarcolor_ns: ^0.4.0
  rxdart: ^0.27.3
  flutter_rating_bar: ^4.0.1
  rich_text_controller: ^1.4.0
  timezone: ^0.8.0
  lottie: 1.2.2
  flutter_dnd: ^0.1.4+1
  flutter_incall_manager:
    git:
      url: https://gitlab.com/dristisushan/flutter-incall-manager
      ref: main
  #    path: ../package/flutter-incall-manager
  new_version: ^0.3.1

  stetho_a1:
    git:
      url: https://gitlab.com/bikrammhz1/flutter_stetho.git
      ref: master

  local_rollbar:
    git:
      url: https://gitlab.com/bikrammhz1/flutter_rollbar.git
      ref: main

  upgrader: ^4.5.0

  voice:
    git:
      url: https://gitlab.com/JoshanTandukar/twilio_voice.git
      ref: main
  #    path: ../twilio_voice

  scroll_to_index:
    git:
      url: https://github.com/edingroot/scroll-to-index.git
      ref: chi-nested-scrollable

  awesome_notifications:
    git:
      url: https://gitlab.com/dristisushan/awesome_notification
      ref: main

  mask_text_input_formatter: ^2.0.0
  flutter_callkit_incoming:
    path: ../../flutter_callkit_incoming
  #    git:
  #      url: https://gitlab.com/dristisushan/flutter_callkit_incoming
  #      ref: main
  store_redirect: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

dependency_overrides:
  firebase_messaging_platform_interface: ^4.1.4

  libphonenumber_plugin:
    git:
      url: https://github.com/charleshan/plugin_libphonenumber.git
      path: libphonenumber_plugin
      ref: 532d4cda9d9a51bcec4416279c4952ce27846900

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/sounds/chime.mp3
    - assets/sounds/sms.mp3
    - assets/sounds/tone.mp3
    - assets/sounds/incoming.wav
    - assets/fonts/CustomIcon.ttf
    - assets/fonts/Heebo-Black.ttf
    - assets/fonts/Heebo-Bold.ttf
    - assets/fonts/Heebo-ExtraBold.ttf
    - assets/fonts/Heebo-Light.ttf
    - assets/fonts/Heebo-Medium.ttf
    - assets/fonts/Heebo-Regular.ttf
    - assets/fonts/Heebo-Thin.ttf
    - assets/fonts/manrope-bold.otf
    - assets/fonts/manrope-extrabold.otf
    - assets/fonts/manrope-light.otf
    - assets/fonts/manrope-medium.otf
    - assets/fonts/manrope-regular.otf
    - assets/fonts/manrope-semibold.otf
    - assets/fonts/manrope-thin.otf
    - assets/images/add_member.png
    - assets/images/block_contact.png
    - assets/images/delete_contact.png
    - assets/images/deleted_workspace.png
    - assets/images/empty_call.png
    - assets/images/empty_contact.png
    - assets/images/empty_member.png
    - assets/images/empty_message.png
    - assets/images/empty_notes.png
    - assets/images/empty_numbers.png
    - assets/images/empty_tags.png
    - assets/images/empty_teams.png
    - assets/images/icon_call.svg
    - assets/images/busyIcon.svg
    - assets/images/noAnswer.svg
    - assets/images/icon_switch.png
    - assets/images/image_credit.png
    - assets/images/invitation.png
    - assets/images/logo.png
    - assets/images/logo_maincolor.png
    - assets/images/no_conversation.png
    - assets/images/no_internet.png
    - assets/images/no_internet_icon.svg
    - assets/images/no_recording.svg
    - assets/images/private_number.png
    - assets/images/smartphone.png
    - assets/images/icon_password_link.png
    - assets/images/icon_cart.png
    - assets/images/icon_no_search_results.png
    - assets/images/image_card.png
    - assets/images/icon_emergency.png
    - assets/images/updateApp.png
    - assets/images/email.png
    - assets/images/auto_records.png
    - assets/images/intl_call_messages.png
    - assets/images/
    - assets/images/icon_upload.png
    - assets/images/icon_upload_text.png
    - assets/images/icon_sync.svg
    - assets/images/call_failed.svg
    - assets/langs/da-DK.json
    - assets/langs/de-DE.json
    - assets/langs/en-US.json
    - assets/langs/es-ES.json
    - assets/langs/fr-FR.json
    - assets/animation/
  fonts:
    - family: HeeboRegular
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: HeeboBlack
      fonts:
        - asset: assets/fonts/Heebo-Black.ttf
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboExtraBold
      fonts:
        - asset: assets/fonts/Heebo-ExtraBold.ttf
    - family: HeeboLight
      fonts:
        - asset: assets/fonts/Heebo-Light.ttf
    - family: HeeboThin
      fonts:
        - asset: assets/fonts/Heebo-Thin.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family: ManropeRegular
      fonts:
        - asset: assets/fonts/manrope-regular.otf
    - family: ManropeMedium
      fonts:
        - asset: assets/fonts/manrope-medium.otf
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/manrope-bold.otf
    - family: ManropeExtraBold
      fonts:
        - asset: assets/fonts/manrope-extrabold.otf
    - family: ManropeLight
      fonts:
        - asset: assets/fonts/manrope-light.otf
    - family: ManropeSemiBold
      fonts:
        - asset: assets/fonts/manrope-semibold.otf
    - family: ManropeThin
      fonts:
        - asset: assets/fonts/manrope-thin.otf
