import "package:flutter/foundation.dart";

class Const {
  Const._();

  static const String ROLLBAR_CONFIGURATION_PRODUCTION =
      "093c2b9d88af4825a9ea08c41e1efa1b";
  static const String ROLLBAR_CONFIGURATION_MVP =
      "79642db8f1fd471aacceb6239a624f19";
  static const String ROLLBAR_CONFIGURATION =
      "9d85a6043ebb4de69c23c7316f36bed2";

  static const String THEME_IS_DARK_THEME = "THEME_IS_DARK_THEME";

  static const String LANGUAGE_LANGUAGE_CODE_KEY = "LANGUAGE_LANGUAGE_CODE_KEY";
  static const String LANGUAGE_COUNTRY_CODE_KEY = "LANGUAGE_COUNTRY_CODE_KEY";
  static const String LANGUAGE_LANGUAGE_NAME_KEY = "LANGUAGE_LANGUAGE_NAME_KEY";

  static const String TRUE = "true";

  static const String PLATFORM = "android";

  static const String FALSE = "false";

  static const String VALUE_HOLDER_USER_ID = "VALUE_HOLDER_USER_ID";
  static const String VALUE_HOLDER_MEMBER_ID = "VALUE_HOLDER_MEMBER_ID";
  static const String VALUE_HOLDER_API_TOKEN = "VALUE_HOLDER_API_TOKEN";
  static const String VALUE_HOLDER_CALL_ACCESS_TOKEN =
      "VALUE_HOLDER_CALL_ACCESS_TOKEN";
  static const String VALUE_HOLDER_REFRESH_TOKEN = "VALUE_HOLDER_REFRESH_TOKEN";
  static const String VALUE_HOLDER_SESSION_ID = "VALUE_HOLDER_SESSION_ID";
  static const String VALUE_HOLDER_NOTIFICATION_TOKEN =
      "VALUE_HOLDER_NOTIFICATION_TOKEN";
  static const String VALUE_HOLDER_ASSIGNED_NUMBER =
      "VALUE_HOLDER_ASSIGNED_NUMBER";
  static const String VALUE_HOLDER_SMS_NOTIFICATION_SETTING =
      "VALUE_HOLDER_SMS_NOTIFICATION_SETTING";
  static const String VALUE_HOLDER_MISSED_CALL_NOTIFICATION_SETTING =
      "VALUE_HOLDER_MISSED_CALL_NOTIFICATION_SETTING";
  static const String VALUE_HOLDER_VOICE_MAIL_NOTIFICATION_SETTING =
      "VALUE_HOLDER_VOICE_MAIL_NOTIFICATION_SETTING";
  static const String VALUE_HOLDER_CHAT_MESSAGE_NOTIFICATION_SETTING =
      "VALUE_HOLDER_CHAT_MESSAGE_NOTIFICATION_SETTING";

  static const String VALUE_HOLDER_USER_NAME = "VALUE_HOLDER_USER_NAME";
  static const String VALUE_HOLDER_USER_FIRST_NAME =
      "VALUE_HOLDER_USER_FIRST_NAME";
  static const String VALUE_HOLDER_USER_LAST_NAME =
      "VALUE_HOLDER_USER_LAST_NAME";
  static const String VALUE_HOLDER_USER_EMAIL = "VALUE_HOLDER_USER_EMAIL";
  static const String VALUE_HOLDER_USER_PASSWORD = "VALUE_HOLDER_USER_PASSWORD";
  static const String VALUE_HOLDER_SELECTED_SOUND =
      "VALUE_HOLDER_SELECTED_SOUND";
  static const String VALUE_HOLDER_DEFAULT_COUNTRY_CODE =
      "VALUE_HOLDER_DEFAULT_COUNTRY_CODE";
  static const String VALUE_HOLDER_DEFAULT_WORKSPACE =
      "VALUE_HOLDER_DEFAULT_WORKSPACE";
  static const String VALUE_HOLDER_WORKSPACE_DETAIL =
      "VALUE_HOLDER_WORKSPACE_DETAIL";
  static const String VALUE_HOLDER_DEFAULT_CHANNEL =
      "VALUE_HOLDER_DEFAULT_CHANNEL";
  static const String VALUE_HOLDER_WORKSPACE_LIST =
      "VALUE_HOLDER_WORKSPACE_LIST";
  static const String VALUE_HOLDER_CHANNEL_LIST = "VALUE_HOLDER_CHANNEL_LIST";
  static const String VALUE_HOLDER_VOICE_TOKEN = "VALUE_HOLDER_VOICE_TOKEN";
  static const String VALUE_HOLDER_PROFILE_PICTURE =
      "VALUE_HOLDER_PROFILE_PICTURE";
  static const String VALUE_HOLDER_USER_ONLINE_STATUS =
      "VALUE_HOLDER_USER_ONLINE_STATUS";
  static const String VALUE_HOLDER_MEMBER_ONLINE_STATUS =
      "VALUE_HOLDER_MEMBER_ONLINE_STATUS";

  ///Default country code according to workspace
  static const String VALUE_HOLDER_INTERCOM_ID = "VALUE_HOLDER_INTERCOM_ID";
  static const String VALUE_PHONE_DEFAULT_COUNTRY_CODE =
      "VALUE_PHONE_DEFAULT_COUNTRY_CODE";
  static const String VALUE_DEFAULT_COUNTRY_CODE_LIST =
      "VALUE_DEFAULT_COUNTRY_CODE_LIST";

  static const String VALUE_HOLDER_USER_OUTGOING_CALL_IN_PROGRESS =
      "VALUE_HOLDER_USER_OUTGOING_CALL_IN_PROGRESS";
  static const String enableCancel = "enableCancel";
  static const String VALUE_HOLDER_USER_INCOMING_CALL_IN_PROGRESS =
      "VALUE_HOLDER_USER_INCOMING_CALL_IN_PROGRESS";
  static const String VALUE_HOLDER_DEFAULT_WORKSPACE_DETAILS =
      "VALUE_HOLDER_DEFAULT_WORKSPACE_DETAILS";
  static const String VALUE_HOLDER_CALL_IN_BACKGROUND =
      "VALUE_HOLDER_CALL_IN_BACKGROUND";
  static const String VALUE_HOLDER_CONTACT_LIST = "VALUE_HOLDER_CONTACT_LIST";
  static const String VALUE_HOLDER_CALL_IS_CONNECTING =
      "VALUE_HOLDER_CALL_IS_CONNECTING";
  static const String VALUE_HOLDER_SELECTED_COUNTRY_CODE =
      "VALUE_HOLDER_SELECTED_COUNTRY_CODE";
  static const String VALUE_HOLDER_CALL_DATA = "VALUE_HOLDER_CALL_DATA";

  ///Plan Overview
  static const String VALUE_HOLDER_PLAN_OVERVIEW = "VALUE_HOLDER_PLAN_OVERVIEW";

  ///Permissions
  static const String ALLOW_WORKSPACE_VIEW_SWITCH_WORKSPACE =
      "ALLOW_WORKSPACE_VIEW_SWITCH_WORKSPACE";
  static const String ALLOW_WORKSPACE_CREATE_NEW_WORKSPACE =
      "ALLOW_WORKSPACE_CREATE_NEW_WORKSPACE";
  static const String ALLOW_WORKSPACE_EDIT_WORKSPACE =
      "ALLOW_WORKSPACE_EDIT_WORKSPACE";
  static const String ALLOW_NAVIGATION_SEARCH = "ALLOW_NAVIGATION_SEARCH";
  static const String ALLOW_NAVIGATION_SHOW_DIALER =
      "ALLOW_NAVIGATION_SHOW_DIALER";
  static const String ALLOW_NAVIGATION_SHOW_DASHBOARD =
      "ALLOW_NAVIGATION_SHOW_DASHBOARD";
  static const String ALLOW_NAVIGATION_SHOW_CONTACT =
      "ALLOW_NAVIGATION_SHOW_CONTACT";
  static const String ALLOW_NAVIGATION_SHOW_SETTING =
      "ALLOW_NAVIGATION_SHOW_SETTING";
  static const String ALLOW_NAVIGATION_ADD_NEW_NUMBER =
      "ALLOW_NAVIGATION_ADD_NEW_NUMBER";
  static const String ALLOW_NAVIGATION_VIEW_NUMBER_DETAILS =
      "ALLOW_NAVIGATION_VIEW_NUMBER_DETAILS";
  static const String ALLOW_NAVIGATION_NUMBER_DND =
      "ALLOW_NAVIGATION_NUMBER_DND";
  static const String ALLOW_NAVIGATION_NUMBER_SETTINGS =
      "ALLOW_NAVIGATION_NUMBER_SETTINGS";
  static const String ALLOW_NAVIGATION_ADD_NEW_MEMBER =
      "ALLOW_NAVIGATION_ADD_NEW_MEMBER";
  static const String ALLOW_NAVIGATION_ADD_NEW_TEAM =
      "ALLOW_NAVIGATION_ADD_NEW_TEAM";
  static const String ALLOW_NAVIGATION_VIEW_TAG_DETAILS =
      "ALLOW_NAVIGATION_VIEW_TAG_DETAILS";
  static const String ALLOW_NAVIGATION_ADD_NEW_TAGS =
      "ALLOW_NAVIGATION_ADD_NEW_TAGS";
  static const String ALLOW_CONTACT_SEARCH_CONTACT =
      "ALLOW_CONTACT_SEARCH_CONTACT";
  static const String ALLOW_CONTACT_ADD_NEW_CONTACT =
      "ALLOW_CONTACT_ADD_NEW_CONTACT";
  static const String ALLOW_CONTACT_CSV_IMPORT = "ALLOW_CONTACT_CSV_IMPORT";
  static const String ALLOW_SHOW_TABLE_VIEW = "ALLOW_SHOW_TABLE_VIEW";
  static const String ALLOW_PROFILE_EDIT_FULL_NAME =
      "ALLOW_PROFILE_EDIT_FULL_NAME";
  static const String ALLOW_PROFILE_EDIT_EMAIL = "ALLOW_PROFILE_EDIT_EMAIL";
  static const String ALLOW_PROFILE_CHANGE_PASSWORD =
      "ALLOW_PROFILE_CHANGE_PASSWORD";
  static const String ALLOW_PROFILE_CHANGE_PROFILE_PICTURE =
      "ALLOW_PROFILE_CHANGE_PROFILE_PICTURE";
  static const String ALLOW_MY_NUMBER_PORT_CONFIG =
      "ALLOW_MY_NUMBER_PORT_CONFIG";
  static const String ALLOW_MY_NUMBER_ADD_NEW_NUMBER =
      "ALLOW_MY_NUMBER_ADD_NEW_NUMBER";
  static const String ALLOW_MY_NUMBER_VIEW_NUMBER_LIST =
      "ALLOW_MY_NUMBER_VIEW_NUMBER_LIST";
  static const String ALLOW_MY_NUMBER_EDIT_DETAILS =
      "ALLOW_MY_NUMBER_EDIT_DETAILS";
  static const String ALLOW_MY_NUMBER_AUTO_RECORD =
      "ALLOW_MY_NUMBER_AUTO_RECORD";
  static const String ALLOW_MY_NUMBER_INTERNATIONAL_CALL =
      "ALLOW_MY_NUMBER_INTERNATIONAL_CALL";
  static const String ALLOW_MY_NUMBER_SHARE_ACCESS =
      "ALLOW_MY_NUMBER_SHARE_ACCESS";
  static const String ALLOW_MY_NUMBER_AUTO_VOICE_MAIL_TRANSCRIPTION =
      "ALLOW_MY_NUMBER_AUTO_VOICE_MAIL_TRANSCRIPTION";
  static const String ALLOW_MY_NUMBER_DELETE = "ALLOW_MY_NUMBER_DELETE";
  static const String ALLOW_MEMBER_ADD_NEW_MEMBER =
      "ALLOW_MEMBER_ADD_NEW_MEMBER";
  static const String ALLOW_MEMBER_MEMBER_LIST = "ALLOW_MEMBER_MEMBER_LIST";
  static const String ALLOW_MEMBER_VIEW_ASSIGNED_NUMBER =
      "ALLOW_MEMBER_VIEW_ASSIGNED_NUMBER";
  static const String ALLOW_MEMBER_DELETE_MEMBER = "ALLOW_MEMBER_DELETE_MEMBER";
  static const String ALLOW_MEMBER_INVITE = "ALLOW_MEMBER_INVITE";
  static const String ALLOW_MEMBER_RE_INVITE = "ALLOW_MEMBER_RE_INVITE";
  static const String ALLOW_TEAM_CREATE_TEAM = "ALLOW_TEAM_CREATE_TEAM";
  static const String ALLOW_TEAM_TEAM_LIST = "ALLOW_TEAM_TEAM_LIST";
  static const String ALLOW_TEAM_EDIT = "ALLOW_TEAM_EDIT";
  static const String ALLOW_TEAM_DELETE = "ALLOW_TEAM_DELETE";
  static const String ALLOW_CONTACT_ADD_NEW_INTEGRATION =
      "ALLOW_CONTACT_ADD_NEW_INTEGRATION";
  static const String ALLOW_CONTACT_INTEGRATION_GOOGLE =
      "ALLOW_CONTACT_INTEGRATION_GOOGLE";
  static const String ALLOW_CONTACT_INTEGRATION_PIPE_DRIVE =
      "ALLOW_CONTACT_INTEGRATION_PIPE_DRIVE";
  static const String ALLOW_CONTACT_IMPORT_CSV = "ALLOW_CONTACT_IMPORT_CSV";
  static const String ALLOW_CONTACT_DELETE_CONTACTS =
      "ALLOW_CONTACT_DELETE_CONTACTS";
  static const String ALLOW_WORKSPACE_UPDATE_PROFILE_PICTURE =
      "ALLOW_WORKSPACE_UPDATE_PROFILE_PICTURE";
  static const String ALLOW_WORKSPACE_CHANGE_NAME =
      "ALLOW_WORKSPACE_CHANGE_NAME";
  static const String ALLOW_WORKSPACE_ENABLE_NOTIFICATION =
      "ALLOW_WORKSPACE_ENABLE_NOTIFICATION";
  static const String ALLOW_WORKSPACE_DELETE = "ALLOW_WORKSPACE_DELETE";
  static const String ALLOW_INTEGRATION_ENABLED = "ALLOW_INTEGRATION_ENABLED";
  static const String ALLOW_INTEGRATION_OTHER_INTEGRATION =
      "ALLOW_INTEGRATION_OTHER_INTEGRATION";
  static const String ALLOW_BILLING_OVERVIEW_CHANGE_PLAN =
      "ALLOW_BILLING_OVERVIEW_CHANGE_PLAN";
  static const String ALLOW_BILLING_OVERVIEW_PURCHASE_CREDIT =
      "ALLOW_BILLING_OVERVIEW_PURCHASE_CREDIT";
  static const String ALLOW_BILLING_OVERVIEW_MANAGE_CARD_ADD =
      "ALLOW_BILLING_OVERVIEW_MANAGE_CARD_ADD";
  static const String ALLOW_BILLING_OVERVIEW_MANAGE_CARD_DELETE =
      "ALLOW_BILLING_OVERVIEW_MANAGE_CARD_DELETE";
  static const String ALLOW_BILLING_OVERVIEW_HIDE_KRISPCALL_BRANDING =
      "ALLOW_BILLING_OVERVIEW_HIDE_KRISPCALL_BRANDING";
  static const String ALLOW_BILLING_OVERVIEW_NOTIFICATION_AUTO_RECHARGE =
      "ALLOW_BILLING_OVERVIEW_NOTIFICATION_AUTO_RECHARGE";
  static const String ALLOW_BILLING_OVERVIEW_CANCEL_SUBSCRIPTION =
      "ALLOW_BILLING_OVERVIEW_CANCEL_SUBSCRIPTION";
  static const String ALLOW_BILLING_SAVE_BILLING_INFO =
      "ALLOW_BILLING_SAVE_BILLING_INFO";
  static const String ALLOW_BILLING_RECEIPTS_VIEW_LIST =
      "ALLOW_BILLING_RECEIPTS_VIEW_LIST";
  static const String ALLOW_BILLING_RECEIPTS_VIEW_INVOICE =
      "ALLOW_BILLING_RECEIPTS_VIEW_INVOICE";
  static const String ALLOW_BILLING_RECEIPTS_DOWNLOAD_INVOICE =
      "ALLOW_BILLING_RECEIPTS_DOWNLOAD_INVOICE";
  static const String ALLOW_DEVICE_SELECT_INPUT_DEVICE =
      "ALLOW_DEVICE_SELECT_INPUT_DEVICE";
  static const String ALLOW_DEVICE_SELECT_OUTPUT_DEVICE =
      "ALLOW_DEVICE_SELECT_OUTPUT_DEVICE";
  static const String ALLOW_DEVICE_ADJUST_INPUT_VOLUME =
      "ALLOW_DEVICE_ADJUST_INPUT_VOLUME";
  static const String ALLOW_DEVICE_ADJUST_OUTPUT_VOLUME =
      "ALLOW_DEVICE_ADJUST_OUTPUT_VOLUME";
  static const String ALLOW_DEVICE_MIC_TEST = "ALLOW_DEVICE_MIC_TEST";
  static const String ALLOW_DEVICE_CANCEL_ECHO = "ALLOW_DEVICE_CANCEL_ECHO";
  static const String ALLOW_DEVICE_REDUCE_NOISE = "ALLOW_DEVICE_REDUCE_NOISE";
  static const String ALLOW_NOTIFICATION_ENABLE_DESKTOP_NOTIFICATION =
      "ALLOW_NOTIFICATION_ENABLE_DESKTOP_NOTIFICATION";
  static const String ALLOW_NOTIFICATION_ENABLE_NEW_CALL_MESSAGE =
      "ALLOW_NOTIFICATION_ENABLE_NEW_CALL_MESSAGE";
  static const String ALLOW_NOTIFICATION_ENABLE_NEW_LEADS =
      "ALLOW_NOTIFICATION_ENABLE_NEW_LEADS";
  static const String ALLOW_NOTIFICATION_ENABLE_FLASH_TASK_BAR =
      "ALLOW_NOTIFICATION_ENABLE_FLASH_TASK_BAR";
  static const String ALLOW_LANGUAGE_SWITCH = "ALLOW_LANGUAGE_SWITCH";

  /// Permissions end
  static const int REQUEST_CODE_MENU_NUMBER_SETTING = 1001;
  static const int REQUEST_CODE_MENU_HOME_FRAGMENT = 1005;
  static const int REQUEST_CODE_MENU_LATEST_PRODUCT_FRAGMENT = 1006;
  static const int REQUEST_CODE_MENU_SELECT_WHICH_USER_FRAGMENT = 1011;
  static const int REQUEST_CODE_MENU_BLOG_FRAGMENT = 1015;
  static const int REQUEST_CODE_MENU_MEMBER_LIST_FRAGMENT = 1016;
  static const int REQUEST_CODE_MENU_GET_STARTED_FRAGMENT = 1017;
  static const int REQUEST_CODE_MENU_CALLS_FRAGMENT = 1020;
  static const int REQUEST_CODE_MENU_DIALER_FRAGMENT = 1026;

  static const int REQUEST_CODE_MENU_CONTACTS_FRAGMENT = 2008;

  static const int NOTIFICATION_CHANNEL_ID_NORMAL = 2;
  static const String NOTIFICATION_CHANNEL_NORMAL = "Normal";
  static const String NOTIFICATION_CHANNEL_NORMAL_TOPIC = "normal";

  static const int NOTIFICATION_CHANNEL_ID_CALL_INCOMING = 3;
  static const String NOTIFICATION_CHANNEL_CALL_INCOMING = "Incoming";
  static const String NOTIFICATION_CHANNEL_CALL_INCOMING_TOPIC = "incoming";

  static const int NOTIFICATION_CHANNEL_ID_SMS = 4;
  static const String NOTIFICATION_CHANNEL_SMS = "SMS Notification";
  static const String NOTIFICATION_CHANNEL_SMS_TOPIC = "sms";

  static const int NOTIFICATION_CHANNEL_ID_CALL_IN_PROGRESS_OUTGOING = 5;
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_OUTGOING =
      "Call In Progress Outgoing";
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_TOPIC_OUTGOING =
      "call_in_progress_outgoing";

  static const int NOTIFICATION_CHANNEL_ID_CALL_IN_PROGRESS_INCOMING = 6;
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_INCOMING =
      "Call In Progress Incoming";
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_TOPIC_INCOMING =
      "call_in_progress_incoming";

  static const int NOTIFICATION_CHANNEL_ID_MISSED_CALL = 7;
  static const String NOTIFICATION_CHANNEL_MISSED_CALL =
      "Missed Call Notification";
  static const String NOTIFICATION_CHANNEL_MISSED_CALL_TOPIC = "missed_call";

  static const int NOTIFICATION_CHANNEL_ID_VOICE_MAIL = 8;
  static const String NOTIFICATION_CHANNEL_VOICE_MAIL =
      "Voice Mail Notification";
  static const String NOTIFICATION_CHANNEL_VOICE_MAIL_TOPIC = "voice_mail";

  static const int NOTIFICATION_CHANNEL_ID_CHAT_MESSAGE = 9;
  static const String NOTIFICATION_CHANNEL_CHAT_MESSAGE =
      "Chat Message Notification";
  static const String NOTIFICATION_CHANNEL_CHAT_MESSAGE_TOPIC = "chat_message";

  static const String PRIVATE_KEY =
      "7wRxs3-VtruSWF2cUNC0trRszwTtHgsfeSBjOCK4dUM=";

  static const String VALUE_HOLDER_USER_DND_TIME_LIST =
      "VALUE_HOLDER_USER_DND_TIME_LIST";

  static const String VALUE_HOLDER_USER_DND_TIME_VALUE =
      "VALUE_HOLDER_USER_DND_TIME_VALUE";

  static const String VALUE_HOLDER_CHANNEL_DND_TIME_LIST =
      "VALUE_HOLDER_CHANNEL_DND_TIME_LIST";

  static const String VALUE_HOLDER_CHANNEL_DND_TIME_VALUE =
      "VALUE_HOLDER_CHANNEL_DND_TIME_VALUE";

  static const int apiTimeout = kDebugMode ? 60 : 60;
  static const int uploadTimeOut = kDebugMode ? 300 : 300;

  static const String OVERFLOW =
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}

class MessageBoxDecorationType {
  static const String TOP = "TOP";
  static const String MIDDLE = "MIDDLE";
  static const String BOTTOM = "BOTTOM";
}

class EndPoints {
  EndPoints._();

  static const String PURCHASE_NUMBER = "/settings/numbers/buy";
  static const String ADD_CARD_DETAILS = "/add-card-detail";
  static const String PLAYSTORE_URL =
      "https://play.google.com/store/apps/details?id=app.krispcall&hl=en";
  static const String APPSTORE_URL =
      "https://apps.apple.com/us/app/facebook/id1597876448";
}
